name: shellcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install shellcheck
      run: sudo apt-get install -y shellcheck

    - name: shellcheck
      run: make lint
